/*
 * kubeflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1alpha2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kubeflow.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.kubeflow.client.models.V1alpha2TFReplicaSpec;

/**
 * TFJobSpec is a desired state description of the TFJob.
 */
@ApiModel(description = "TFJobSpec is a desired state description of the TFJob.")

public class V1alpha2TFJobSpec {
  @SerializedName("cleanPodPolicy")
  private String cleanPodPolicy = null;

  @SerializedName("tfReplicaSpecs")
  private Map<String, V1alpha2TFReplicaSpec> tfReplicaSpecs = new HashMap<String, V1alpha2TFReplicaSpec>();

  public V1alpha2TFJobSpec cleanPodPolicy(String cleanPodPolicy) {
    this.cleanPodPolicy = cleanPodPolicy;
    return this;
  }

   /**
   * CleanPodPolicy defines the policy to kill pods after TFJob is succeeded. Default to Running.
   * @return cleanPodPolicy
  **/
  @ApiModelProperty(value = "CleanPodPolicy defines the policy to kill pods after TFJob is succeeded. Default to Running.")
  public String getCleanPodPolicy() {
    return cleanPodPolicy;
  }

  public void setCleanPodPolicy(String cleanPodPolicy) {
    this.cleanPodPolicy = cleanPodPolicy;
  }

  public V1alpha2TFJobSpec tfReplicaSpecs(Map<String, V1alpha2TFReplicaSpec> tfReplicaSpecs) {
    this.tfReplicaSpecs = tfReplicaSpecs;
    return this;
  }

  public V1alpha2TFJobSpec putTfReplicaSpecsItem(String key, V1alpha2TFReplicaSpec tfReplicaSpecsItem) {
    this.tfReplicaSpecs.put(key, tfReplicaSpecsItem);
    return this;
  }

   /**
   * TFReplicaSpecs is map of TFReplicaType and TFReplicaSpec specifies the TF replicas to run. For example,   {     \&quot;PS\&quot;: TFReplicaSpec,     \&quot;Worker\&quot;: TFReplicaSpec,   }
   * @return tfReplicaSpecs
  **/
  @ApiModelProperty(required = true, value = "TFReplicaSpecs is map of TFReplicaType and TFReplicaSpec specifies the TF replicas to run. For example,   {     \"PS\": TFReplicaSpec,     \"Worker\": TFReplicaSpec,   }")
  public Map<String, V1alpha2TFReplicaSpec> getTfReplicaSpecs() {
    return tfReplicaSpecs;
  }

  public void setTfReplicaSpecs(Map<String, V1alpha2TFReplicaSpec> tfReplicaSpecs) {
    this.tfReplicaSpecs = tfReplicaSpecs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha2TFJobSpec v1alpha2TFJobSpec = (V1alpha2TFJobSpec) o;
    return Objects.equals(this.cleanPodPolicy, v1alpha2TFJobSpec.cleanPodPolicy) &&
        Objects.equals(this.tfReplicaSpecs, v1alpha2TFJobSpec.tfReplicaSpecs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cleanPodPolicy, tfReplicaSpecs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha2TFJobSpec {\n");
    
    sb.append("    cleanPodPolicy: ").append(toIndentedString(cleanPodPolicy)).append("\n");
    sb.append("    tfReplicaSpecs: ").append(toIndentedString(tfReplicaSpecs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

