/*
 * kubeflow
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1alpha2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.kubeflow.client.apis;

import org.kubeflow.client.ApiException;
import io.kubernetes.client.models.V1APIGroup;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KubeflowOrgApi
 */
@Ignore
public class KubeflowOrgApiTest {

    private final KubeflowOrgApi api = new KubeflowOrgApi();

    
    /**
     * 
     *
     * get information of a group
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAPIGroupTest() throws ApiException {
        V1APIGroup response = api.getAPIGroup();

        // TODO: test validations
    }
    
}
